---
# This playbook deploys war file to tomcat server

- hosts: tomcat-servers
  remote_user: ec2-user
  become: yes
  become_method: sudo

  tasks:
    - name: Copy WAR file to target machine's tomcat's webapp folder
      copy:
        src: target/CounterWebApp.war
        dest: /usr/share/tomcat/webapps
        owner: tomcat
        group: tomcat
        mode: 0644
    
